version: '3' #dockerfile version
services:
  parser:
    image: python:2
    tty: true
    stdin_open: true
    command: bash
    links:
      - db
    ports:
      - 8888:3306
    volumes:
      - .:/app
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  db:
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    environment:
        MYSQL_ROOT_PASSWORD: test
